#include <iostream>
#include <vector>
#include <string>
#include <cstdlib>   // for atoi

# ifndef __FLEX_LEXER_H
#  define yyFlexLexer mathFlexLexer
#  include <FlexLexer.h>
#  undef yyFlexLexer
# endif


// ---------- Token definition ----------
enum TokenType { NUMBER, OPERATOR, UNKNOWN };

struct Token {
    TokenType type;
    std::string lexeme;
    int int_val;      // valid when type == NUMBER
    char op_char;     // valid when type == OPERATOR
};

// ---------- Custom lexer class ----------
// We derive from the Flex-generated class CalcFlexLexer
class mathLexer : public mathFlexLexer {
public:
    std::vector<Token> tokens;   // will hold all tokens from input

    // The main scanning function – we must override it.
    // The actual body is generated by Flex from the rules below.
    int yylex() override;
};

